# Generated by Django 3.1.2 on 2020-10-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name='Fecha creación'),
        ),
    ]
