# Generated by Django 3.1.2 on 2020-10-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201030_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
    ]
